seed: 42
trainer:
  gpus: 1
  num_nodes: 1
  max_epochs: 8
  max_steps: null
  accumulate_grad_batches: 1
  gradient_clip_val: 1
  amp_level: O1
  precision: 16
  accelerator: ddp
  checkpoint_callback: false
  logger: false
  log_every_n_steps: 1
  val_check_interval: 1.0
  resume_from_checkpoint: null
exp_manager:
  exp_dir: /home/nxingyu2/project/
  name: Punctuation_with_Domain_discriminator
  create_tensorboard_logger: true
  create_checkpoint_callback: true
base_path: /home/nxingyu2/data
tmp_path: /home/nxingyu2/data/tmp
log_dir: /home/nxingyu2/project/Punctuation_with_Domain_discriminator/2021-03-17_08-35-04
model:
  nemo_path: null
  transformer_path: bert-base-uncased
  unfrozen: 0
  maximum_unfrozen: 2
  unfreeze_step: 1
  test_every_layer: false
  punct_label_ids:
  - ''
  - ','
  - .
  - '?'
  label_map:
    '!': .
    '-': ','
    ':': ','
    …: .
    —: ','
    ;: .
  no_space_label: '#'
  test_chunk_percent: null
  punct_class_weight_factor: 0.2
  punct_class_weights: null
  dataset:
    data_dir: /home/nxingyu2/data
    labelled: null
    unlabelled:
    - /home/nxingyu2/data/switchboardutt_processed
    low_resource_labelled_count: 64
    max_seq_length: 128
    pad_label: ''
    ignore_extra_tokens: false
    ignore_start_end: false
    use_cache: false
    num_workers: 4
    pin_memory: false
    drop_last: true
    num_labels: 9
    num_domains: 1
    test_unlabelled: true
    attach_label_to_end: null
    pad_start: 0
    train_ds:
      shuffle: true
      num_samples: -1
      batch_size: 8
      manual_len: 0
    validation_ds:
      shuffle: true
      num_samples: -1
      batch_size: 32
  tokenizer:
    tokenizer_name: bert-base-uncased
    vocab_file: null
    tokenizer_model: null
    special_tokens: null
  language_model:
    pretrained_model_name: bert-base-uncased
    lm_checkpoint: null
    config_file: null
    config: null
  punct_head:
    punct_num_fc_layers: 2
    fc_dropout: 0.1
    activation: gelu
    log_softmax: false
    use_transformer_init: true
    loss: dice
    bilstm: false
    dice_loss:
      epsilon: 0.05
      alpha: 4
      macro_average: true
    focal_loss:
      alpha: 6
  domain_head:
    predict_labelled: false
    domain_num_fc_layers: 1
    fc_dropout: 0.1
    activation: gelu
    log_softmax: false
    use_transformer_init: true
    loss: dice
    gamma: null
    gamma_factor: 0
    pooling: attention
    idx_conditioned_on: 0
    weight_tokens: true
    weight:
    - 1
    dice_loss:
      epsilon: 0.01
      alpha: 6
      macro_average: true
    focal_loss:
      alpha: 6
  frozen_lr:
  - 0.005
  - 0.0005
  - 5.0e-05
  - 1.0e-05
  - 1.0e-05
  - 1.0e-07
  - 1.0e-08
  optim:
    name: adamw
    lr: 0.01
    weight_decay: 0.0
    sched:
      name: CosineAnnealing
      warmup_steps: null
      warmup_ratio: 0.1
      min_lr: 1.0e-08
      last_epoch: -1
      monitor: val_loss
      reduce_on_plateau: false
